local Plug = require('user.vim-plug')

Plug.begin()

Plug('nvim-lualine/lualine.nvim')
Plug('arkav/lualine-lsp-progress')
Plug('linrongbin16/lsp-progress.nvim')
Plug('rizzatti/dash.vim')
Plug('itchyny/lightline.vim')
Plug('mengelbrecht/lightline-bufferline')
Plug('folke/tokyonight.nvim', {branch = 'main'})
Plug('ellisonleao/gruvbox.nvim')
Plug('olivercederborg/poimandres.nvim')
Plug('shinchu/lightline-gruvbox.vim')
Plug('edkolev/tmuxline.vim')
Plug('scrooloose/nerdtree')
Plug('ryanoasis/vim-devicons')
Plug('preservim/nerdcommenter')
Plug('tpope/vim-fugitive')
Plug('tpope/vim-obsession')
Plug('airblade/vim-gitgutter')
Plug('junegunn/goyo.vim')
Plug('mhinz/vim-startify')

Plug.ends()
